In [3]:
a=[[1,2,3],[4,5,6]]
print(a)
l=[[1,2,3],[4,5]]
l[0][2]

[[1, 2, 3], [4, 5, 6]]


3

In [1]:
#Creating 2 d array
i1D=[i for  i in range(10)]
#print(i1D)
i2D=[[0,0,0] for i in range(10)]
#print(i2D)
i2D1=[[j for j in range(5)] for i in range(10)]
print(i2D1)
i2D2=[[5*i+j for j in range(5)] for i in range(10)]
i2D2

[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]]


[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34],
 [35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44],
 [45, 46, 47, 48, 49]]

Taking input into array


In [33]:
str=input().strip().split(" ")
n=int(str[0])
m=int(str[1])
#Assuming all input  in a single line
l=[int(i) for i in input().strip().split(' ')]
l
#reshaping
out=[]
for i in range(n):
    out.append([])
    for j in range(m):
        out[i].append(l[i*m+j])
print(out)
#same in one line
out2=[ [ l[i*m+j] for j in range(m)] for i in range(n)]
out2

2 3
1 2 3 4 5 6
[[1, 2, 3], [4, 5, 6]]


[[1, 2, 3], [4, 5, 6]]

## WAVE PRINT


In [39]:
n=len(out2)
m=len(out2[0])
for j in range(m):
    if (j%2==0):
        for i in range(n):
            print (out2[i][j],end=" ")
    else:
        for i in range(n-1,-1,-1):
            print(out2[i][j],end=" ")

1 4 5 2 3 6 

import this as alias ............
from x import y

In [41]:
import math as m
m.sqrt(4)

2.0

# NUMPY


Python lists are generally not fast. different elements cant be stored in same contiguous memory. not compact.
Numpy has elements of same type stored in compact 
internally c code in that so fast.

In [3]:
import numpy as np

In [48]:
l=[1,2,3]
print(np.array(l))
f=[1,2,'3']
np.array(f) #Converted but now each element is a string

[1 2 3]


array(['1', '2', '3'],
      dtype='<U11')

In [53]:
arr=np.zeros(10)
print(arr)
arr.dtype

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


dtype('float64')

In [60]:
arr2=np.ones(4,int)
arr2[0]='5' #implicitly converts '5' to 5
print(arr2)
arr2.dtype

[5 1 1 1]


dtype('int32')

In [4]:
#2d array
print(np.zeros([2,3]))
print(np.zeros([2,3,4])) #3d

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [61]:
#slicing and indexing same as normal lists

In [65]:
arr2.shape

(4,)

In [78]:
ama=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(ama[0])
print(ama[:,0]) #means all rows in col 0
print(ama[:2,1:3]) #means till row1 and  in col 1,2

[1 2 3]
[ 1  4  7 10]
[[2 3]
 [5 6]]


In [79]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
#NUMPY OPERATIONS

In [83]:
#does element wise stuff
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+2) #normal list would have just appended
print(b*2)
print(a+b)
print(a**2)
b

[3 4 5]
[10 12 14]
[ 6  8 10]
[1 4 9]


array([5, 6, 7])

In [86]:
b.mean()
b.sum()

18

In [87]:
#example need distance between  two points 
#say its in 3 dimension x,y,z
#two points are a and b
a=np.array([1,2,3])
b=np.array([5,6,7])
d=((a-b)**2).sum()
m.sqrt(d)

6.928203230275509

In [88]:
#example 2
x=np.array([1,3,5,6])
((x-x.mean())**2).sum()

14.75

In [90]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[10,20],[30,40]])
a1.dot(a2) #DOT PRODUCT

array([[ 70, 100],
       [150, 220]])

Numpy has np.mat as well which is specially for matrices . That is 
strictly 2d array.  THEY BEHAVE MORE LIKE MATRICES.
Adv- If I do a*b , its not going to do element wise multiplication.  Its gonna take their product.



In [93]:
a=np.array([5,1,2,1])
a.mean()

2.25

In [94]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
a.dot(b)

26

In [96]:
a = np.matrix('1 2 4; 3 4 5')
a.shape
a

matrix([[1, 2, 4],
        [3, 4, 5]])

In [112]:
    a=np.sum([[4, 1], [4, 5]], axis=0)
    print(a)
    a=np.sum([[4, 1], [4, 5]], axis=1)
    print(a)

[8 6]
[5 9]
