In [1]:
import numpy as np
data=np.loadtxt("boston_x_y_train.csv",delimiter=",")
xtest=np.loadtxt("boston_x_test.csv",delimiter=",")
xtest
data

array([[ -0.40784991,  -0.48772236,  -1.2660231 , ...,   0.41057102,
         -1.09799011,  37.9       ],
       [ -0.40737368,  -0.48772236,   0.24705682, ...,   0.29116915,
         -0.52047412,  21.4       ],
       [  0.1251786 ,  -0.48772236,   1.01599907, ...,  -3.79579542,
          0.89107588,  12.7       ],
       ..., 
       [ -0.40831101,  -0.48772236,   0.24705682, ...,   0.33206621,
         -0.33404299,  20.8       ],
       [ -0.41061997,  -0.48772236,  -1.15221381, ...,   0.203235  ,
         -0.74475218,  22.6       ],
       [  0.34290895,  -0.48772236,   1.01599907, ...,   0.38787479,
         -1.35871335,  50.        ]])

In [4]:
xtrain=data[:,:-1]
ytrain=data[:,-1]

print(xtest.shape)
print(xtrain.shape)
print(ytrain.shape)
xtrain

(127, 13)
(379, 13)
(379,)


array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ..., 
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [10]:
from sklearn.linear_model import SGDRegressor
clf=SGDRegressor(max_iter=100)
clf.fit(xtrain,ytrain)

SGDRegressor(alpha=0.0001, average=False, epsilon=0.1, eta0=0.01,
       fit_intercept=True, l1_ratio=0.15, learning_rate='invscaling',
       loss='squared_loss', max_iter=100, n_iter=None, penalty='l2',
       power_t=0.25, random_state=None, shuffle=True, tol=None, verbose=0,
       warm_start=False)

In [11]:
clf.coef_

array([-0.93542977,  0.72940469, -0.08030132,  0.78182708, -2.17853367,
        2.36133969,  0.106937  , -2.94119712,  2.35632608, -1.51774332,
       -2.25843913,  0.58735679, -4.26416109])

In [12]:
clf.intercept_

array([ 22.68372023])

In [13]:
ytest=clf.predict(xtest)

In [14]:
np.savetxt("GDAssignmentBoston.csv",ytest,delimiter=",")