In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
X=np.array([[1.,-1.,2.],
          [2.,0.,0.],
          [0.,1.,-1.]])

In [13]:
X_scaled=preprocessing.scale(X)
#it makes mean to be 0 and variance to be 1 by default
#can pass parameters to change default
print(X_scaled)
print(X_scaled.mean(axis=0))
print(X_scaled.std(axis=0))


[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[ 0.  0.  0.]
[ 1.  1.  1.]


#scale xtrain and xtest together
#coz otherwise xtrain will be scaled acc to its mean and train with its own other mean
#so option 1 dont do it seperately
#but in real scenarios we train .. test data comes from customer later on
#so best way OPTION 2
#scale on xtrain-----> store  the parameters on which scaling done(mean etc)
#when testing data comes---->use same parameters for it
for this use 
preprocessing.StandardScaler() #works same but returns object which can be further used

In [10]:
scaler=preprocessing.StandardScaler()
scaler.fit(X) #object fitted 
#can use this object to transform anything using the same parameters

scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [11]:
X_test=[[1,1,0]] #need to give 2 d array -- as it hopes array of diff datapoints - here one
scaler.transform(X_test) #scaled the data as per parameters learned while training

array([[ 0.        ,  1.22474487, -0.26726124]])

MIN MAX SCALER
MAX ABSOLUTE SCALER 
etc also available
#All scalers take parameters

In [21]:
from sklearn.preprocessing import StandardScaler
data=[[0,3],[9,4],[2,7],[1,1]]
Scaler=StandardScaler()
Scaler.fit(data)
first=Scaler.transform(data)
second=Scaler.transform([[2,13],[1,4],[10,7],[1,9]])
print(first.std(axis=0))
print(second.std(axis=0))
print(first.mean())
#coz mean will change acc to more data previously mean was made 0
#but for second it must  be according to first
print(second.mean())
print(first.sum())
print(second.sum())

[ 1.  1.]
[ 1.06770783  1.50996689]
0.0
1.10994116266
0.0
8.87952930128
